name: chat_bot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts:
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.3
  # google_mlkit_language_id: ^0.13.0
  translator: ^1.0.3+1
  google_translation:
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  fluttertoast: ^8.2.12
  lottie: ^3.3.1
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  vibration: ^3.1.3
  haptic_feedback: ^0.5.1+1
  flutter_native_splash: ^2.4.4
  flutter_sound: ^9.28.0
  path_provider: ^2.1.5
  ffmpeg_kit_flutter_new: ^1.6.1
  # record: 
  mime: ^1.0.4
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  dio: ^5.4.0
  device_info_plus: 
  flutter_secure_storage:
  uuid: ^4.0.0
  just_audio: ^0.9.36
  # audioplayers: ^5.2.1

  

#
#  ## Splash screen configuration should be at the root level (not under flutter:)
#flutter_native_splash:
#    color: "#000000"
#    android_12:
#    background_image: assets/images/sitalogo.png
#    android: true
#    ios: true

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/sitalogo.png" # or update to your actual icon path
  remove_alpha_ios: true
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_native_splash:
  color: "#2b3e2b"
  image: assets/images/sitalogo.png
#  branding: assets/images/sitalogo.png
#  branding_bottom_padding: 24
  color_dark: "#2b3e2b"
  image_dark: assets/images/sitalogo.png
#  branding_dark: assets/images/sitalogo.png

  android_12:
    image: assets/images/sitalogo.png
    icon_background_color: "#2b3e2b"
    image_dark: assets/images/sitalogo.png
    icon_background_color_dark: "#2b3e2b"

  web: false